### ISSUE TITLE
Using plugin on Ionic 4 

### ISSUE THREAD

**Issue by giarauz** [CleverTap/clevertap-cordova#48]
Hi guys, im trying to integrate clevertap cordova plugin to a new ionic 4 project using the following steps:

ionic cordova plugin add clevertap-cordova@latest --variable CLEVERTAP_ACCOUNT_ID="TEST-xxx-xxx-xxxx" --variable CLEVERTAP_TOKEN="TEST-xxx-xxx"

npm install --save @ionic-native/clevertap

adding references on app.modules.ts.

add google-services.json on root project

ionic cordova platform add android 

I got this error on cordova plugin instalation:
Installing "clevertap-cordova" for android
config file undefined requested for changes not found at /home/user/Projects/ionic_projects/clevertap/platforms/android/undefined, ignoring

When run ionic cordova run android --device and access Android Studio Logcat, i get this error when CleverTap plugin try to start

2020-02-07 07:45:31.913 29636-29866/io.clevetabDemo.starter W/System.err: java.lang.NoClassDefFoundError: com.clevertap.android.sdk.InAppFCManager
2020-02-07 07:45:31.913 29636-29866/io.clevetabDemo.starter W/System.err:     at com.clevertap.android.sdk.CleverTapAPI.<init>(CleverTapAPI.java:130)
2020-02-07 07:45:31.913 29636-29866/io.clevetabDemo.starter W/System.err:     at com.clevertap.android.sdk.CleverTapAPI.instanceWithConfig(CleverTapAPI.java:509)
2020-02-07 07:45:31.913 29636-29866/io.clevetabDemo.starter W/System.err:     at com.clevertap.android.sdk.CleverTapAPI.getDefaultInstance(CleverTapAPI.java:456)
2020-02-07 07:45:31.913 29636-29866/io.clevetabDemo.starter W/System.err:     at com.clevertap.android.sdk.CleverTapAPI.getDefaultInstance(CleverTapAPI.java:475)
2020-02-07 07:45:31.914 29636-29866/io.clevetabDemo.starter W/System.err:     at com.clevertap.cordova.CleverTapPlugin.initialize(CleverTapPlugin.java:60)

ionic info

Ionic:

   Ionic CLI                     : 5.4.4 (/home/user/.npm-global/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 5 other plugins)

Utility:

   cordova-res : 0.8.0 (update available: 0.9.0)
   native-run  : 0.2.9 (update available: 0.3.0)

System:

   Android SDK Tools : 26.1.1 (/home/user/Android/Sdk)
   NodeJS            : v12.14.1 (/usr/bin/node)
   npm               : 6.13.4
   OS                : Linux 5.3

**Comment by darshanclevertap** [comment]
@giarauz Can you share the contents of your `build.gradle` file? Have you added the CleverTap Android SDK as a dependency?

**Comment by darshanclevertap** [comment]
@giarauz This is because of Android Gradle plugin v3.3.0. Please update it. For more information, go through the following links - 
https://github.com/CleverTap/clevertap-android-sdk/issues/15
