### ISSUE TITLE
Set minimum requirement of AGP to 3.3.1

### ISSUE THREAD

**Issue by sagrawal31** [CleverTap/clevertap-cordova#60]
# Description

We have been trying to figure out this issue for 4-5 days. We installed this plugin and tried to run. Although the build was working fine and the app was getting launched, but in the dashboard, it was showing the **Integration is pending**.

Then we tried to debug the issue by reading the tons of logs from `adb` and got this issue:

```
04-27 09:19:16.925  9548  9699 W System.err: java.lang.VerifyError: Verifier rejected class com.clevertap.android.sdk.InAppFCManager: int[] com.clevertap.android.sdk.InAppFCManager.getInAppCountsFromPersistentStore(java.lang.String) failed to verify: int[] com.clevertap.android.sdk.InAppFCManager.getInAppCountsFromPersistentStore(java.lang.String): [0x3B] register v2 has type Conflict but expected Integer (declaration of 'com.clevertap.android.sdk.InAppFCManager' appears in /data/app/com.onmobile.kids.demo-v0AEa5ovZLwvoVPtRQKZyw==/base.apk)
04-27 09:19:16.925  9548  9699 W System.err: 	at com.clevertap.android.sdk.CleverTapAPI.<init>(CleverTapAPI.java:141)
04-27 09:19:16.926  9548  9699 W System.err: 	at com.clevertap.android.sdk.CleverTapAPI.instanceWithConfig(CleverTapAPI.java:528)
04-27 09:19:16.926  9548  9699 W System.err: 	at com.clevertap.android.sdk.CleverTapAPI.getDefaultInstance(CleverTapAPI.java:479)
04-27 09:19:16.926  9548  9699 W System.err: 	at com.clevertap.android.sdk.CleverTapAPI.getDefaultInstance(CleverTapAPI.java:494)
04-27 09:19:16.926  9548  9699 W System.err: 	at com.clevertap.cordova.CleverTapPlugin.initialize(CleverTapPlugin.java:60)
04-27 09:19:16.926  9548  9699 W System.err: 	at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:57)
04-27 09:19:16.926  9548  9699 W System.err: 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
04-27 09:19:16.927  9548  9699 W System.err: 	at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
04-27 09:19:16.927  9548  9699 W System.err: 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
04-27 09:19:16.927  9548  9699 W System.err: 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
04-27 09:19:16.927  9548  9699 W System.err: 	at android.os.MessageQueue.nativePollOnce(Native Method)
04-27 09:19:16.927  9548  9699 W System.err: 	at android.os.MessageQueue.next(MessageQueue.java:326)
04-27 09:19:16.927  9548  9699 W System.err: 	at android.os.Looper.loop(Looper.java:181)
04-27 09:19:16.927  9548  9699 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:65)
```

On further research, we found out that an issue was created in the CleverTap Android SDK https://github.com/CleverTap/clevertap-android-sdk/issues/15.

Reading the entire discussion, we figured out that upgrading the Android Gradle Plugin to minimum of `3.3.1` fixes this issue as commented here https://github.com/CleverTap/clevertap-android-sdk/issues/15#issuecomment-461396398.

So this Cordova plugin should define the `build.gradle` with `classpath 'com.android.tools.build:gradle:3.3.1'` or at least this should be added in the README.md.

# Environment

```shell
Ionic:

   Ionic CLI          : 6.5.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.3

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.3, (and 24 other plugins)

Utility:

   cordova-res (update available: 0.13.0) : 0.5.1
   native-run (update available: 1.0.0)   : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/shashank/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v10.16.0 (/usr/local/bin/node)
   npm               : 6.9.0
   OS                : macOS Catalina
   Xcode             : Xcode 11.2.1 Build version 11B500
```

**Comment by darshanclevertap** [comment]
@sagrawal31 Have you tested this? Adding an extra build.gradle file doesn't change the app's Gradle plugin version

**Comment by sagrawal31** [comment]
If I remember correctly, this works. I have tried that in the past.

**Comment by darshanclevertap** [comment]
I will test it again, do I need to remove and add the android platform before or after adding the plugin?

**Comment by hvaughan3** [comment]
I had to build a cordova hook to update build.gradle directly. The build-extras.gradle is not able to overwrite dependencies (from what I have read) so it will not be able to overrule what is already in your build.gradle.

Here is my hook:

```
const fs = require('fs')
const path = require('path')

module.exports = function (context) {
  console.log('Running Update Android Gradle Plugin')

  const rootDir = context.opts.projectRoot
  const androidPlatformPath = path.join(rootDir, '/platforms/android/build.gradle')

  // make sure the gradle file exists
  try {
    fs.accessSync(androidPlatformPath, fs.F_OK)
  } catch (e) {
    console.error(`Could not find android gradle file at ${androidPlatformPath}`)
    return
  }

  let fileContents

  try {
    fileContents = fs.readFileSync(androidPlatformPath, 'UTF-8')
  } catch (e) {
    console.error('Could not load gradle file text')
    return
  }

  fileContents = fileContents.replace('com.android.tools.build:gradle:3.3.0', 'com.android.tools.build:gradle:3.3.1')

  fs.writeFileSync(androidPlatformPath, fileContents)

  console.log('Finished Update Android Gradle Plugin')
}
```

**Comment by darshanclevertap** [comment]
@hvaughan3 This is amazing!

I was doing it manually in my sample project as the `build.gradle` with the new AGP version wasn't updating the existing AGP version. 

@sagrawal31 Can you use the hook provided by @hvaughan3 till Cordova updates their Android platform to update to the new AGP version?

**Comment by sagrawal31** [comment]
Thank you for the update @darshanclevertap & @hvaughan3 

I'll try this out.

**Comment by sagrawal31** [comment]
Like I mentioned above, I have seen people updating the AGP versions via `build.gradle` from plugins https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/src/android/build.gradle#L12. Not sure why it is not working here. Need to check.

I'll try the solution provided by @hvaughan3 temporarily.
